name: starbucks_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.2

  #state management
  flutter_riverpod: ^2.1.3
  riverpod: ^2.1.1

  #service
  dio: ^4.0.6

  #routing
  auto_route: ^5.0.4

  #core
  after_layout: ^1.2.0

  #maps
  flutter_map: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  #routing
  auto_route_generator: ^5.0.3

  #generator
  flutter_gen_runner: ^5.1.0+1
  build_runner: ^2.3.3

flutter_gen:
  output: lib/gen/
  integrations:
    flutter_svg: true
  assets:
    enabled: true


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

 